services:
  frontend:
    image: todo-front-prod
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-front-prod

  server:
    image: todo-back-prod
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://teppo:salainen@mongo:27017/todo_db
    container_name: todo-back-prod
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: teppo
      MONGO_INITDB_ROOT_PASSWORD: salainen
      MONGO_INITDB_DATABASE: todo_db
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    container_name: mongo

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: redis

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - server

volumes:
  mongo_data:
