services:
  frontend:
    image: todo-front-dev
    build:
      context: ./todo-frontend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./todo-frontend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    # ports:
    #   - 5173:5173 # Nginx handles porting
    container_name: todo-front-dev # This will name the container todo-front-dev
  # debug-helper:
  #   image: busybox

  server:
    image: todo-back-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      - REDIS_URL=redis://redis:6379
      # - MONGO_URL=mongodb://teppo:salainen@mongo:27017/todo_db
      - MONGO_URL=mongodb://teppo:salainen@mongo-dev:27017/todo_db
    # ports:
    #   - 3000:3000 # Nginx handles porting
    container_name: todo-back-dev
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: teppo
      MONGO_INITDB_ROOT_PASSWORD: salainen
      MONGO_INITDB_DATABASE: todo_db
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    container_name: mongo-dev

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"] # Overwrite the CMD
    volumes: # Declare the volume
      - ./todo-backend/redis_data:/data
    container_name: redis-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-front
    depends_on:
      - frontend # wait for the frontend container to be started
      - server
volumes:
  mongo_data:
