services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: teppo
      MONGO_INITDB_ROOT_PASSWORD: salainen
      MONGO_INITDB_DATABASE: todo_db
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  mongo_data:
